# Generated by Django 5.2.16 on 2026-07-17 13:10

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esistatus", "0003_esistatus_total_endpoints"),
    ]

    operations = [
        migrations.AddField(
            model_name="esistatus",
            name="esi_name",
            field=models.CharField(
                blank=True,
                help_text="The name ESI is currently going by. The three letters have never once meant the same thing twice.",
                max_length=250,
                null=True,
            ),
        ),
    ]
