# Generated by Django 5.2.17 on 2026-08-22 10:02

# Standard Library
import uuid

# Django
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esistatus", "0004_esi_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="esistatus",
            options={
                "default_permissions": (),
                "ordering": ["-timestamp"],
                "verbose_name": "ESI Endpoint Status",
                "verbose_name_plural": "ESI Endpoint Statuses",
            },
        ),
        migrations.AddField(
            model_name="esistatus",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="The timestamp of the history entry.",
            ),
        ),
        migrations.AddField(
            model_name="esistatus",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddIndex(
            model_name="esistatus",
            index=models.Index(
                fields=["timestamp"], name="esistatus_e_timesta_bce509_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="esistatus",
            name="id",
        ),
        migrations.AlterField(
            model_name="esistatus",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="esistatus",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The timestamp of the history entry.",
            ),
        ),
    ]
